version: '3'

volumes:
  backup-rabbitmq-integration-poc:
    driver: local

networks:
  integration-poc-network:

services:

  rabbitmq:
    build:
      context: .
      dockerfile: rabbitmq.dockerfile
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15672
      - 15671:15671
    container_name: rabbitmq-integration-poc
    networks:
      - integration-poc-network
    volumes:
      - ./docker/rabbitmq/config:/var/lib/rabbitmq/config